# Generated by Django 5.2.1 on 2025-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
            ],
        ),
    ]
